### PR TITLE
Basic Bundle Support

### PR DESCRIPTION
**Pull request by Nemo157**
WIP implementation for #3

### CODE REVIEW

**Comment by a-dma** [comment]
Hi, is this still in progress? I tried to get something going directly with crates.io (https://github.com/rust-lang/crates.io/issues/1113) but people seem to think it's not their concern... I having the possibility of easily obtaining license files would be extremely valuable

**Comment by Nemo157** [comment]
I haven't touched this since January and can't remember the exact state of it. A quick skim of the code it looks like it should be pretty much working for MIT/Apache-2.0 (and supporting the rest of the OSI licenses should be straightforward).

There is difficulty around crates that use non-standard licenses, for example [`byteorder`](https://crates.io/crates/byteorder) which is a pretty fundamental crate that would be included in a lot of applications is licensed under MIT/Unlicense. It does include the text of the Unlicense in its repository (and presumably source bundle) but doesn't reference that in any way from its `Cargo.toml`.

There is another question I have, which is whether the current approach of having hardcoded text for each license (including placeholders) is strictly correct, or whether this tool needs to actually get the real license file from each dependency. If it is the later then the same issue with non-standard licenses also applies to the standard licenses, generally crates that specify there license by name don't bother to reference the file as well.

Those issues aside, I'd be pretty happy to get this merged as is and just add some caveats to the output. I can probably find time to rebase this and add those caveats in the next few days. For now if you want to test this (although it will likely crash from missing license files very quickly) you can install it via `cargo install --git https://github.com/Nemo157/cargo-lichking --rev bundle` and run it with `cargo lichking bundle`.

**Comment by a-dma** [comment]
Yeah, I know what you mean, that's why I was trying to push for a more standardized approach a bit higher up in the hierarchy. Not having to have this logic in individual crates would make life easier.

I believe that having the generic text of the license without the proper attribution is incorrect and only slightly better than not giving any attribution whatsoever. How would you feel about doing shallow-clones of the dependencies and trying to extract license files from there? GitHub even supports svn so in theory it's possible to use `svn cat` for these.
I still believe there should be a centralized and official license repository...

**Comment by Nemo157** [comment]
> I believe that having the generic text of the license without the proper attribution is incorrect and only slightly better than not giving any attribution whatsoever. How would you feel about doing shallow-clones of the dependencies and trying to extract license files from there? GitHub even supports svn so in theory it's possible to use svn cat for these.

If the generic license is not good enough I guess I can drop that and try and write something to search for the license file. Most of the time it shouldn't be hard to detect.

I believe the actual files for each package are available because this is using `cargo` as a library behind the scenes to walk the dependency tree and read the manifests (which must be pulling the dependency into the cache as the manifest is not stored in the index).

It's going to mean some ridiculously massive bundles though, for example this project has 85 dependencies with an MIT license and 65 with Apache-2.0 (with a lot of overlap). That looks to be almost 800KiB of text just for those licenses. Oh well, licensing is always a pain I guess.

**Comment by a-dma** [comment]
Yeah, I think there is no easy win there, licensing is messy.

If you can easily access the manifest through the lib than it shouldn't be _too_ painful. There are a lot of funny names to check for and sometimes people do embed the license text in the `README` file, which makes it very tricky to extract, but at list this is a more than reasonable effort.

As far as the size goes, I think that since this is just an option it's fine to produce big artifacts.

Thanks for putting effort in this!

**Comment by Nemo157** [comment]
@a-dma I finally got round to finishing the text matching part of this. It currently only has a few licenses added, but it should be usable in this state. If you're still interested in this it would be great if you could try it and provide some feedback.

**Comment by a-dma** [comment]
Great, thanks! I'll have a look around and let you know.

**Comment by a-dma** [comment]
This is nice and seems to be working quite well.
Some licenses are not picked up even tho they have license files that follow "standard" naming conventions. For example [rust-commoncrypto](https://github.com/malept/rust-commoncrypto/blob/master/LICENSE) and [ansi-term](https://github.com/ogham/rust-ansi-term/blob/master/LICENCE) (UK spelling here).

Just thinking out loud here, but maybe a quick nice addition would be to be able to specify a directory and have the tool write one file per crate.

**Comment by Nemo157** [comment]
> Some licenses are not picked up even tho they have license files that follow "standard" naming conventions. For example rust-commoncrypto and ansi-term (UK spelling here).

`commoncrypto` hit the same issue that a lot of `*-sys` crates do, they have the license file at the root of the repository but don't include it with the source code when publishing crates contained in subfolders. This was fixed yesterday with https://github.com/malept/rust-commoncrypto/pull/2, so the next release of `commoncrypto` should include it.

For `ansi-term` I've opened a merge request to move it to the US-English spelling. Despite being an NZ-English speaker I didn't actually realise that 'licence' is the UK-English spelling, I guess I've only really encountered the word in relation to programming where I try to stick to US-English. Since it is "correct" I'll add it as another alias to check against.

> Just thinking out loud here, but maybe a quick nice addition would be to be able to specify a directory and have the tool write one file per crate.

Yep, that's why I added the `variant` option defaulting to `inline`, I plan to support at least:

 * single file with all licenses inlined
 * single file with just license identifiers
 * single file with identifiers + folder of license texts
 * rust source file with license identifiers + text as constants (for embedding directly into an application)

**Comment by a-dma** [comment]
Cool!

How about being able to match file names through a config file? Sounds like an easy way to handle oddballs.

**Pull request merged**
