### PR TITLE
Update cargo

### LINKED ISSUE #43: Update cargo dependency
Would you please update the dependency on `cargo` to the latest version, 0.31?  I'd like to package `cargo-lichking` for Debian and build it against `cargo` 0.31 so that we don't have to package an old version of `cargo`.

### PR DESCRIPTION
**Pull request by kraai**
Closes #43

### CODE REVIEW

**Comment by Nemo157** [comment]
Thanks, this looks great. I'll update the Rust versions on travis to get this passing and merge it tonight (I need to do some maintenance on the travis config here anyway).

**Comment by kraai** [comment]
Would it be possible to release a new version that includes this change?

**Comment by Nemo157** [comment]
[Travis should release it soon](https://travis-ci.org/Nemo157/cargo-lichking/builds/464255091). Was going to do it last night, but adding Windows to CI has made everything really slow...

**Comment by kraai** [comment]
Thanks!  I'm packaging it for Debian now.

**Pull request merged**
